import { spawnSync } from "node:child_process";
import { randomBytes as nodeRandomBytes } from "node:crypto";
import { chmod, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  configurationOrder,
  createServiceRoleToken,
  databaseUrlRules,
  directSecretKeys,
  expectedOrigins,
  expectedTarget,
  isPlaceholder,
  parseEnv,
  validateConfiguration,
} from "./config.mjs";

const roleNames = Object.freeze({
  owner: "agency_workload_owner",
  migrator: "agency_workload_migrator",
  runtime: "agency_workload_runtime",
  auth: "supabase_auth_admin",
  backup: "agency_workload_backup",
});

function randomToken(randomBytes) {
  return randomBytes(48).toString("base64url");
}

function uniqueRandomToken(randomBytes, forbidden) {
  for (let attempt = 0; attempt < 32; attempt += 1) {
    const token = randomToken(randomBytes);
    if (!forbidden.has(token)) {
      forbidden.add(token);
      return token;
    }
  }
  throw new Error("Unable to generate unique local secret material");
}

function databaseUrl(username, hostname, randomBytes) {
  const url = new URL(
    `postgresql://${username}@${hostname}:${expectedTarget.AW_POSTGRES_HOST_PORT}/${expectedTarget.AW_DATABASE_NAME}`,
  );
  url.password = randomToken(randomBytes);
  return url.toString();
}

function urlNeedsGeneration(value) {
  if (!value || isPlaceholder(value)) return true;
  try {
    return isPlaceholder(decodeURIComponent(new URL(value).password));
  } catch {
    return false;
  }
}

function updateEnvironmentText(existingText, values, changedKeys) {
  if (!existingText) {
    const lines = [
      "# Development-only configuration generated by npm run local:bootstrap.",
      "# Never commit this file or reuse these values outside local development.",
      "",
    ];
    for (const key of configurationOrder) {
      lines.push(key === "" ? "" : `${key}=${values.get(key)}`);
    }
    return `${lines.join("\n")}\n`;
  }

  const seen = new Set();
  const lines = existingText.split(/\r?\n/).map((line) => {
    const match = line.match(/^\s*(?:export\s+)?([A-Z][A-Z0-9_]*)\s*=/);
    if (!match || !values.has(match[1])) return line;
    const key = match[1];
    seen.add(key);
    return changedKeys.has(key) ? `${key}=${values.get(key)}` : line;
  });

  for (const key of configurationOrder) {
    if (key && !seen.has(key)) lines.push(`${key}=${values.get(key)}`);
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

export function createLocalEnvironment(
  existingText,
  { now = Math.floor(Date.now() / 1000), randomBytes = nodeRandomBytes } = {},
) {
  const values = existingText ? parseEnv(existingText) : new Map();
  const changedKeys = new Set();

  for (const [key, value] of Object.entries(expectedTarget)) {
    if (!values.has(key) || isPlaceholder(values.get(key))) {
      values.set(key, value);
      changedKeys.add(key);
    }
  }

  const legacyOrigins = new Map([["API_ORIGIN", "http://localhost:3101"]]);
  for (const [key, value] of Object.entries(expectedOrigins)) {
    if (
      !values.has(key) ||
      isPlaceholder(values.get(key)) ||
      values.get(key) === legacyOrigins.get(key)
    ) {
      values.set(key, value);
      changedKeys.add(key);
    }
  }

  for (const [key, rule] of Object.entries(databaseUrlRules)) {
    if (urlNeedsGeneration(values.get(key))) {
      values.set(key, databaseUrl(rule.username, rule.hostname, randomBytes));
      changedKeys.add(key);
    }
  }

  for (const key of directSecretKeys.filter(
    (candidate) => candidate !== "GOTRUE_SERVICE_ROLE_KEY",
  )) {
    if (!values.has(key) || isPlaceholder(values.get(key))) {
      values.set(key, randomToken(randomBytes));
      changedKeys.add(key);
    }
  }

  if (
    !values.has("GOTRUE_SERVICE_ROLE_KEY") ||
    isPlaceholder(values.get("GOTRUE_SERVICE_ROLE_KEY"))
  ) {
    values.set(
      "GOTRUE_SERVICE_ROLE_KEY",
      createServiceRoleToken(values.get("GOTRUE_JWT_SECRET"), { now }),
    );
    changedKeys.add("GOTRUE_SERVICE_ROLE_KEY");
  }

  assertExpectedTarget(values);
  const failures = validateConfiguration(values, { template: false });
  if (failures.length > 0) {
    throw new Error(
      `local configuration is unsafe:\n${failures.map((item) => `- ${item}`).join("\n")}`,
    );
  }

  return {
    changed: changedKeys.size > 0,
    text: updateEnvironmentText(existingText, values, changedKeys),
    values,
  };
}

export function createRotatedEnvironment(
  existingText,
  { now = Math.floor(Date.now() / 1000), randomBytes = nodeRandomBytes } = {},
) {
  if (!existingText) throw new Error("Secret rotation requires an existing local environment");
  const previousValues = parseEnv(existingText);
  assertExpectedTarget(previousValues);
  const existingFailures = validateConfiguration(previousValues, { template: false });
  if (existingFailures.length > 0) {
    throw new Error(
      `local configuration is unsafe:\n${existingFailures.map((item) => `- ${item}`).join("\n")}`,
    );
  }

  const values = new Map(previousValues);
  const changedKeys = new Set([...Object.keys(databaseUrlRules), ...directSecretKeys]);
  const forbidden = new Set(directSecretKeys.map((key) => previousValues.get(key)));
  for (const key of Object.keys(databaseUrlRules)) {
    forbidden.add(passwordFrom(previousValues, key));
  }

  for (const key of Object.keys(databaseUrlRules)) {
    const url = new URL(previousValues.get(key));
    url.password = uniqueRandomToken(randomBytes, forbidden);
    values.set(key, url.toString());
  }

  for (const key of ["GOTRUE_JWT_SECRET", "PENDING_AUTH_KEY", "SESSION_SECRET"]) {
    values.set(key, uniqueRandomToken(randomBytes, forbidden));
  }
  values.set(
    "GOTRUE_SERVICE_ROLE_KEY",
    createServiceRoleToken(values.get("GOTRUE_JWT_SECRET"), { now }),
  );

  const failures = validateConfiguration(values, { template: false });
  if (failures.length > 0) {
    throw new Error(
      `rotated configuration is unsafe:\n${failures.map((item) => `- ${item}`).join("\n")}`,
    );
  }

  return {
    rotatedKeyCount: changedKeys.size,
    text: updateEnvironmentText(existingText, values, changedKeys),
    values,
  };
}

export function assertExpectedTarget(values) {
  for (const [key, expected] of Object.entries(expectedTarget)) {
    if (values.get(key) !== expected) throw new Error(`${key} does not match the approved target`);
  }
}

function sqlLiteral(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

function passwordFrom(values, key) {
  return decodeURIComponent(new URL(values.get(key)).password);
}

function loginRoleBlock(name, password, connectionLimit) {
  return `
DO $bootstrap$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = ${sqlLiteral(name)}) THEN
    CREATE ROLE ${name};
  END IF;
END
$bootstrap$;
ALTER ROLE ${name} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT CONNECTION LIMIT ${connectionLimit} PASSWORD ${sqlLiteral(password)};
`;
}

export function buildMaintenanceSql(values) {
  const database = expectedTarget.AW_DATABASE_NAME;
  return `
\\set ON_ERROR_STOP on
DO $bootstrap$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${roleNames.owner}') THEN
    CREATE ROLE ${roleNames.owner};
  END IF;
END
$bootstrap$;
ALTER ROLE ${roleNames.owner} WITH NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOINHERIT;
DO $bootstrap$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN
    CREATE ROLE postgres NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOINHERIT;
  ELSIF EXISTS (
    SELECT 1 FROM pg_roles
    WHERE rolname = 'postgres'
      AND (rolcanlogin OR rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication)
  ) THEN
    RAISE EXCEPTION 'refusing elevated postgres compatibility role';
  END IF;
END
$bootstrap$;
${loginRoleBlock(roleNames.migrator, passwordFrom(values, "MIGRATION_DATABASE_URL"), 5)}
${loginRoleBlock(roleNames.runtime, passwordFrom(values, "DATABASE_URL"), 20)}
${loginRoleBlock(roleNames.auth, passwordFrom(values, "GOTRUE_DATABASE_URL"), 20)}
${loginRoleBlock(roleNames.backup, passwordFrom(values, "BACKUP_DATABASE_URL"), 2)}
SELECT format(
  'CREATE DATABASE %I WITH OWNER %I ENCODING %L TEMPLATE template0',
  '${database}',
  '${roleNames.owner}',
  'UTF8'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${database}')
\\gexec
ALTER DATABASE ${database} OWNER TO ${roleNames.owner};
REVOKE ALL ON DATABASE ${database} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${database} TO ${roleNames.migrator}, ${roleNames.runtime}, ${roleNames.auth}, ${roleNames.backup};
ALTER ROLE ${roleNames.migrator} IN DATABASE ${database} SET search_path = app, pg_catalog;
ALTER ROLE ${roleNames.runtime} IN DATABASE ${database} SET search_path = app, pg_catalog;
ALTER ROLE ${roleNames.auth} IN DATABASE ${database} SET search_path = auth, pg_catalog;
ALTER ROLE ${roleNames.backup} IN DATABASE ${database} SET search_path = app, auth, pg_catalog;
`;
}

export function buildDatabaseSql() {
  return `
\\set ON_ERROR_STOP on
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM ${roleNames.migrator}, ${roleNames.runtime}, ${roleNames.auth}, ${roleNames.backup};
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION ${roleNames.owner};
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION ${roleNames.auth};
ALTER SCHEMA app OWNER TO ${roleNames.owner};
ALTER SCHEMA auth OWNER TO ${roleNames.auth};
REVOKE ALL ON SCHEMA app FROM PUBLIC;
REVOKE ALL ON SCHEMA auth FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA app TO ${roleNames.migrator};
GRANT USAGE ON SCHEMA app TO ${roleNames.runtime}, ${roleNames.backup};
GRANT USAGE, CREATE ON SCHEMA auth TO ${roleNames.auth};
GRANT USAGE ON SCHEMA auth TO ${roleNames.backup};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO ${roleNames.runtime};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA app TO ${roleNames.runtime};
GRANT SELECT ON ALL TABLES IN SCHEMA app, auth TO ${roleNames.backup};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA app, auth TO ${roleNames.backup};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.owner} IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${roleNames.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.owner} IN SCHEMA app
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${roleNames.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.owner} IN SCHEMA app
  GRANT SELECT ON TABLES TO ${roleNames.backup};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.migrator} IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${roleNames.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.migrator} IN SCHEMA app
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${roleNames.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.migrator} IN SCHEMA app
  GRANT SELECT ON TABLES TO ${roleNames.backup};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.auth} IN SCHEMA auth
  GRANT SELECT ON TABLES TO ${roleNames.backup};
ALTER DEFAULT PRIVILEGES FOR ROLE ${roleNames.auth} IN SCHEMA auth
  GRANT SELECT ON SEQUENCES TO ${roleNames.backup};
`;
}

export function buildPasswordRotationSql(values) {
  return `
\\set ON_ERROR_STOP on
BEGIN;
ALTER ROLE ${roleNames.migrator} WITH PASSWORD ${sqlLiteral(passwordFrom(values, "MIGRATION_DATABASE_URL"))};
ALTER ROLE ${roleNames.runtime} WITH PASSWORD ${sqlLiteral(passwordFrom(values, "DATABASE_URL"))};
ALTER ROLE ${roleNames.auth} WITH PASSWORD ${sqlLiteral(passwordFrom(values, "GOTRUE_DATABASE_URL"))};
ALTER ROLE ${roleNames.backup} WITH PASSWORD ${sqlLiteral(passwordFrom(values, "BACKUP_DATABASE_URL"))};
COMMIT;
`;
}

export function psqlInvocation(database) {
  if (
    ![expectedTarget.AW_POSTGRES_MAINTENANCE_DB, expectedTarget.AW_DATABASE_NAME].includes(database)
  ) {
    throw new Error("database is not an approved bootstrap target");
  }
  return {
    command: "docker",
    args: [
      "exec",
      "-i",
      expectedTarget.AW_POSTGRES_CONTAINER,
      "psql",
      "--username",
      expectedTarget.AW_POSTGRES_SUPERUSER,
      "--dbname",
      database,
      "--no-psqlrc",
      "--set",
      "ON_ERROR_STOP=1",
      "--quiet",
    ],
  };
}

function shellLiteral(value) {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function credentialProbeInvocation(values, { expectAuthentication }) {
  const checks = Object.entries(databaseUrlRules)
    .map(([key, rule]) => {
      const rejectedCondition = expectAuthentication
        ? '[ "$authenticated" -ne 0 ]'
        : '[ "$authenticated" -eq 0 ]';
      return `
PGPASSWORD=${shellLiteral(passwordFrom(values, key))} psql --host host.docker.internal --port ${expectedTarget.AW_POSTGRES_HOST_PORT} --username ${rule.username} --dbname ${expectedTarget.AW_DATABASE_NAME} --no-password --tuples-only --no-align --command 'SELECT 1' >/dev/null 2>&1
authenticated=$?
if ${rejectedCondition}; then
  exit 71
fi`;
    })
    .join("\n");

  return {
    command: "docker",
    args: [
      "run",
      "--rm",
      "-i",
      "--add-host",
      "host.docker.internal:host-gateway",
      "postgres:16-alpine",
      "sh",
    ],
    input: `set +x\n${checks}\nexit 0\n`,
  };
}

function defaultRunner({ command, args, input }) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    input,
    maxBuffer: 1024 * 1024,
    windowsHide: true,
  });
  return { status: result.status, stdout: result.stdout ?? "", error: result.error };
}

function runOrThrow(runner, invocation, input, operation) {
  const result = runner({ ...invocation, input });
  if (result.error || result.status !== 0) {
    throw new Error(`${operation} failed without exposing subprocess output`);
  }
  return result.stdout;
}

function verifyContainer(runner) {
  const output = runOrThrow(
    runner,
    {
      command: "docker",
      args: [
        "inspect",
        "--format",
        '{{.Name}}|{{.Config.Image}}|{{.State.Running}}|{{with (index .NetworkSettings.Ports "5432/tcp")}}{{(index . 0).HostPort}}{{end}}',
        expectedTarget.AW_POSTGRES_CONTAINER,
      ],
    },
    undefined,
    "PostgreSQL container inspection",
  ).trim();
  const [name, image, running, hostPort] = output.split("|");
  if (
    name !== `/${expectedTarget.AW_POSTGRES_CONTAINER}` ||
    !/^postgres:16(?:[-.]|$)/.test(image) ||
    running !== "true" ||
    hostPort !== expectedTarget.AW_POSTGRES_HOST_PORT
  ) {
    throw new Error("PostgreSQL container does not match the approved name, version, or port");
  }
}

async function writePrivateEnvironment(path, text, runner) {
  const temporary = join(dirname(path), `.env.${process.pid}.tmp`);
  try {
    await writeFile(temporary, text, { encoding: "utf8", flag: "wx", mode: 0o600 });
    await secureEnvironmentFile(temporary, runner);
    await rename(temporary, path);
  } finally {
    await rm(temporary, { force: true });
  }
}

async function secureEnvironmentFile(path, runner) {
  if (process.platform !== "win32") {
    await chmod(path, 0o600);
    return;
  }

  const identity = runOrThrow(
    runner,
    { command: "whoami", args: ["/user", "/fo", "csv", "/nh"] },
    undefined,
    "Windows identity lookup",
  );
  const sid = identity.match(/,"([A-Z0-9-]+)"\s*$/i)?.[1];
  if (!sid) throw new Error("Windows identity lookup returned an unexpected result");

  runOrThrow(
    runner,
    {
      command: "icacls",
      args: [
        path,
        "/inheritance:r",
        "/grant:r",
        `*${sid}:(F)`,
        "*S-1-5-18:(F)",
        "*S-1-5-32-544:(F)",
      ],
    },
    undefined,
    "Windows environment permission update",
  );
}

export async function bootstrapLocal({ root, runner = defaultRunner } = {}) {
  const envPath = join(root, ".env");
  let existingText = "";
  try {
    existingText = await readFile(envPath, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw new Error("Unable to read local environment file");
  }

  const environment = createLocalEnvironment(existingText);
  if (environment.changed) await writePrivateEnvironment(envPath, environment.text, runner);
  await secureEnvironmentFile(envPath, runner);

  verifyContainer(runner);
  runOrThrow(
    runner,
    psqlInvocation(expectedTarget.AW_POSTGRES_MAINTENANCE_DB),
    buildMaintenanceSql(environment.values),
    "PostgreSQL role and database bootstrap",
  );
  runOrThrow(
    runner,
    psqlInvocation(expectedTarget.AW_DATABASE_NAME),
    buildDatabaseSql(environment.values),
    "PostgreSQL schema and privilege bootstrap",
  );

  return { environmentChanged: environment.changed };
}

export async function rotateLocalSecrets({
  confirmed,
  now = Math.floor(Date.now() / 1000),
  postRotationVerify,
  randomBytes = nodeRandomBytes,
  root,
  runner = defaultRunner,
} = {}) {
  if (confirmed !== true) throw new Error("Secret rotation requires explicit confirmation");

  const envPath = join(root, ".env");
  let existingText;
  try {
    existingText = await readFile(envPath, "utf8");
  } catch {
    throw new Error("Secret rotation requires an existing readable local environment");
  }

  const previousValues = parseEnv(existingText);
  const rotated = createRotatedEnvironment(existingText, { now, randomBytes });
  verifyContainer(runner);

  let databaseRotated = false;
  try {
    runOrThrow(
      runner,
      psqlInvocation(expectedTarget.AW_POSTGRES_MAINTENANCE_DB),
      buildPasswordRotationSql(rotated.values),
      "PostgreSQL password rotation",
    );
    databaseRotated = true;
    await writePrivateEnvironment(envPath, rotated.text, runner);
  } catch {
    if (databaseRotated) {
      try {
        runOrThrow(
          runner,
          psqlInvocation(expectedTarget.AW_POSTGRES_MAINTENANCE_DB),
          buildPasswordRotationSql(previousValues),
          "PostgreSQL password rollback",
        );
      } catch {
        throw new Error("Secret rotation failed and database password rollback also failed");
      }
    }
    throw new Error("Secret rotation failed; previous configuration remains active");
  }

  const previousCredentialProbe = credentialProbeInvocation(previousValues, {
    expectAuthentication: false,
  });
  runOrThrow(
    runner,
    previousCredentialProbe,
    previousCredentialProbe.input,
    "Previous database credential rejection check",
  );
  const currentCredentialProbe = credentialProbeInvocation(rotated.values, {
    expectAuthentication: true,
  });
  runOrThrow(
    runner,
    currentCredentialProbe,
    currentCredentialProbe.input,
    "Rotated database credential authentication check",
  );

  if (postRotationVerify) {
    await postRotationVerify({
      currentValues: rotated.values,
      previousValues,
    });
  }

  return {
    previousDatabaseCredentialsRejected: true,
    rotatedKeyCount: rotated.rotatedKeyCount,
  };
}

export function rotationSummaryLines(result) {
  return [
    `Rotated ${result.rotatedKeyCount} Agency Workload local secret values.`,
    "Rejected all previous dedicated-role database credentials.",
    "Preserved the existing database, schemas, and data.",
  ];
}
